**Introduction to pandas Data Structures**

**Series**

In [ ]:
# creating series
import pandas as pd
import numpy as np

series1 = pd.Series([100,500,200,300,450,600])
print(series1)
# print(series1.array)
# print(series1.index)
# print(series1.dtype)

# index1 = ["A","C","B","D","E","F"]
# index1_shuffled = np.array(index1).copy()
# np.random.shuffle(index1_shuffled)
# print(index1)
# print(index1_shuffled)
# series2 = pd.Series(series1.array, index = index1_shuffled)
# print(series2)

# series1.index = index1
# print(series1)

series3 = pd.Series([1000,500,700,900,120],index=["California","Texas","Ohio","Utah","Berlin"],dtype=int)
print(series3)

# series4 = pd.Series([2000,5000,100],index=["Tokyo","Shanghai","California"],dtype=int)
# print(series4)

# print(series3+series4)

print(pd.isna(series3))
print(pd.notna(series3))
# series3[0] = pd.NA
series3["Texas"] = pd.NA
print(pd.isna(series3))
print(pd.notna(series3))

print(np.log(series3),"\n")
series3.name = "Population of cities"
series3.index.name = "Cities"
print(series3)

0    100
1    500
2    200
3    300
4    450
5    600
dtype: int64
California    1000
Texas          500
Ohio           700
Utah           900
Berlin         120
dtype: int64
California    False
Texas         False
Ohio          False
Utah          False
Berlin        False
dtype: bool
California    True
Texas         True
Ohio          True
Utah          True
Berlin        True
dtype: bool
California    False
Texas          True
Ohio          False
Utah          False
Berlin        False
dtype: bool
California     True
Texas         False
Ohio           True
Utah           True
Berlin         True
dtype: bool
California    6.907755
Texas              NaN
Ohio          6.551080
Utah          6.802395
Berlin        4.787492
dtype: float64

Cities
California    1000.0
Texas            NaN
Ohio           700.0
Utah           900.0
Berlin         120.0
Name: Population of cities, dtype: float64

**DataFrame**

In [ ]:
# creating dataframes
import pandas as pd
import numpy as np

df1 = pd.DataFrame({"A":[10,20,25,15,50],"B":[90,56,23,54,24],"C":[65,45,26,33,66],"D":[67,43,78,97,57]},index=["John","Mark","Sam","Akay","Simen"])
df1["E"] = [80,45,24,56,43]
df1.index.name = "Students"
df1.columns.name = "Subjects"
df1.columns
df1.index
df1["Pass"] = ((df1["A"] + df1["B"] + df1["C"] + df1["D"] + df1["E"])/5) > 40
# print(df1)

del df1["Pass"]
df1

df2 = pd.DataFrame({"Delhi":{2021:101,2022:102,2023:103},        # takes outer keys as columns and union of inner keys as row indices
                    "Mumbai":{2021:103,2024:104,2023:105}})
df2.columns.name = "Cities"
df2.index.name = "Year"
print(df2,df2.dtypes,"\n")
print(df2.T,df2.T.dtypes,"\n")

print(df2.to_numpy(),df2.to_numpy().dtype,"\n")
print(df2.T.to_numpy(),df2.T.to_numpy().dtype)

Cities  Delhi  Mumbai
Year
2021    101.0   103.0
2022    102.0     NaN
2023    103.0   105.0
2024      NaN   104.0 Cities
Delhi     float64
Mumbai    float64
dtype: object

Year     2021   2022   2023   2024
Cities
Delhi   101.0  102.0  103.0    NaN
Mumbai  103.0    NaN  105.0  104.0 Year
2021    float64
2022    float64
2023    float64
2024    float64
dtype: object

[[101. 103.]
 [102.  nan]
 [103. 105.]
 [ nan 104.]] float64

[[101. 102. 103.  nan]
 [103.  nan 105. 104.]] float64

**Index Objects**

In [ ]:
# df1 = pd.DataFrame([["A","B","C","D"],[1,2,3,4,5]])
# df1 = pd.DataFrame({"New Delhi":{"ratings":pd.Series(np.arange(6)),"rankings":pd.Series(np.arange(6,11))},
#                     "Mumbai":{"ratings":pd.Series(np.arange(6,11)),"rankings":pd.Series(np.arange(6))}})
df1 = pd.DataFrame({"A":pd.Series(np.arange(6,11)),"B":pd.Series([1,2,3,4,5]),"C":pd.Series(np.arange(5,10)),"D":pd.Series([10,2,5,7,5])})
df1

pd.Index(df1.index)
index1 = pd.Index(["A","B","C","D","A"])

df2 = pd.DataFrame({"1":[1,2,3,4,5],"2":[6,7,8,9,10]}, index = index1)
print(df2,"\n")
df2.loc["A"]

   1   2
A  1   6
B  2   7
C  3   8
D  4   9
A  5  10

   1   2
A  1   6
A  5  10

**Essential Functionality**

**Reindexing**

In [ ]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({1:[1,2,3,4,5],2:[4,3,5,2,5]})
print(df1)

df2 = df1.reindex([0,2,4])
print(df2)

df3 = pd.DataFrame(np.arange(9).reshape(3,3),index=["A","B","C"],columns=["A1","B1","C1"])
print(df3,"\n")

df4 = df3.reindex(index=["A","D","C"])
print(df4,"\n")

# df4 = df4.reindex(columns=["A1","D1","B1","C1"])
df4 = df4.reindex(["A1","C1","D1","E1","B1"],axis="columns",method="ffill")
print(df4)

   1  2
0  1  4
1  2  3
2  3  5
3  4  2
4  5  5
   1  2
0  1  4
2  3  5
4  5  5
   A1  B1  C1
A   0   1   2
B   3   4   5
C   6   7   8

    A1   B1   C1
A  0.0  1.0  2.0
D  NaN  NaN  NaN
C  6.0  7.0  8.0

    A1   C1   D1   E1   B1
A  0.0  2.0  2.0  2.0  1.0
D  NaN  NaN  NaN  NaN  NaN
C  6.0  8.0  8.0  8.0  7.0

**Dropping Entries from an Axis**

In [ ]:
# dropping index and columns from a series
import pandas as pd
import numpy as np

# series1= pd.Series(np.arange(11)+10,index=np.arange(1,12))
# print(series1)

# # series2 = series1.drop(11)
# # print(series2)
# series2 = series1.drop([1,5,11])
# print(series2)

# dropping index and columns from a dataframe
df1 = pd.DataFrame(np.arange(16).reshape(4,4), index = np.arange(1,5), columns = ["A","B","C","D"])
df1.index.name = "rows"
df1.columns.name = "characters"
print(df1)

# df2 = df1.drop(1)
# df2 = df1.drop([1,4])
# df2 = df1.drop("B",axis="columns")
df2 = df1.drop(["B","C"],axis=1)
print(df2)

characters   A   B   C   D
rows
1            0   1   2   3
2            4   5   6   7
3            8   9  10  11
4           12  13  14  15
characters   A   D
rows
1            0   3
2            4   7
3            8  11
4           12  15

**Indexing, Selection, and Filtering**

In [ ]:
# indexing, selection and filtering by direct [] brackets, .loc and .iloc methods in series
# series1 = pd.Series(np.arange(6)**2+10,index=["A","B","C","D","E","F"])
# print(series1)

# print(series1["A"])
# series1[["A","B","F","D"]]
# series1[1]
# series1[[1,5,2]]

# series1.loc["C"]
# series1.loc[["A","C","A","B"]]
# series1.iloc[0]
# series1.iloc[[0,5,2,3]]

# indexing, selection and filtering by direct [] brackers, .loc and .iloc methods in dataframes
df1 = pd.DataFrame(np.random.standard_normal((5,5)), index = np.arange(1,6), columns = ["A","B","C","C","D"])
print(df1)

df1["A"]
df1[["C","B","A"]]
df1[:4]
# df1[:4,2] # --> gives error, use .loc or .iloc preferably

df1.loc[1]
df1.loc[[1,2],["A","B"]]

# df1.loc[0] # --> gives error since we don't have any row with index label '0'
print(df1.iloc[0]) #--> returns 1st row as series

df1.iloc[[0,3,2,4],[3,0,2,4]]

df2 = pd.DataFrame(np.random.randint(5,21,(4,4)), index = ["->1","->2","->3","->4"], columns = ["A","B","C","D"])
print(df2)

print(df2>10)
df2[df2>10]

print(df2.loc[df2.C>4])
# df2.iloc[df2.C>4] # --> gives error since boolean based indexing can only be performed using .loc method and can't be performed using .iloc method
df2.iloc[:,:3][df2.C>4]

print(df2.at["->2","B"])
print(df2.iat[2,3])

          A         B         C         C         D
1 -1.525501 -0.537305  0.504448 -0.347863  0.405801
2  1.308940 -1.905710  0.216449 -0.648412  1.132881
3 -2.161339  1.761268  0.074821  0.074960 -0.831316
4 -2.592600 -1.692374  0.163412 -0.374479 -1.912802
5 -1.017440 -0.078622  0.477475  0.394196  1.601899
A   -1.525501
B   -0.537305
C    0.504448
C   -0.347863
D    0.405801
Name: 1, dtype: float64
      A   B   C   D
->1   7  20   5  20
->2   5  19   6  20
->3   9  20  20   5
->4  15   6  11  17
         A      B      C      D
->1  False   True  False   True
->2  False   True  False   True
->3  False   True   True  False
->4   True  False   True   True
      A   B   C   D
->1   7  20   5  20
->2   5  19   6  20
->3   9  20  20   5
->4  15   6  11  17
19
5

**Arithmetic and Data Alignment**

In [ ]:
# arithmetic operations between differently indexed objects (series/dataframes)
# operations between dataframe and series
# operations with fill values specified as well

import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.random.randint(0,11,20).reshape(4,5), index = ["New Delhi","Mumbai","Kolkata","Chennai"], columns = list("abcde"))
print(df1)

series1 = df1.loc["New Delhi"]
print(series1,"\n")

print(df1-series1)

series2 = df1.loc[:,"b"]
print(series2,"\n")
print(df1.sub(series2,axis="index"))

df1 + series1

df2 = pd.DataFrame(np.random.standard_normal((3,3)), index = ["Bombay","New Delhi","Kolkata"], columns = list("abc"))
print(df2)

df1 + df2

df1-df2

            a   b   c   d  e
New Delhi   5   6   9   9  6
Mumbai      2  10  10   8  1
Kolkata    10   8   7  10  7
Chennai     1   0  10   8  9
a    5
b    6
c    9
d    9
e    6
Name: New Delhi, dtype: int64

           a  b  c  d  e
New Delhi  0  0  0  0  0
Mumbai    -3  4  1 -1 -5
Kolkata    5  2 -2  1  1
Chennai   -4 -6  1 -1  3
New Delhi     6
Mumbai       10
Kolkata       8
Chennai       0
Name: b, dtype: int64

           a  b   c  d  e
New Delhi -1  0   3  3  0
Mumbai    -8  0   0 -2 -9
Kolkata    2  0  -1  2 -1
Chennai    1  0  10  8  9
                  a         b         c
Bombay     0.558953 -0.732389 -0.668950
New Delhi  0.648473  1.475790  0.132169
Kolkata   -0.449385  1.247309  2.043650

                   a         b         c   d   e
Bombay           NaN       NaN       NaN NaN NaN
Chennai          NaN       NaN       NaN NaN NaN
Kolkata    10.449385  6.752691  4.956350 NaN NaN
Mumbai           NaN       NaN       NaN NaN NaN
New Delhi   4.351527  4.524210  8.867831 NaN NaN

**Function Application and Mapping**

In [ ]:
# define a function and apply it to a dataframe through the apply method (both axes)
# use numpy ufuncs on dataframes
# use dataframes in built methods as well
# use applymap function as well

import pandas as pd
import numpy as np

# creating a dataframe of students marks with rows as students and columns as subjects
df1 = pd.DataFrame({"John":np.random.randint(1,101,5),"Aray":np.random.randint(1,101,5),"Sam":np.random.randint(1,101,5),"Jay":np.random.randint(1,101,5)})
df1 = df1.T
df1.index.name = "Students"
df1.columns.name = "Subjects"
df1.columns = ["English","Hindi","Maths","Science","Social Science"]
print(df1)

# numpy ufuncs
# print(np.sqrt(df1))
# print(np.exp(df1))

# defining a function manually to return max and min marks in subjects (subjects-wise)
def f1(x):
  return pd.Series([x.max(),x.min()], index=["max","min"])

# defining a function manually to return deviation from median marks (considering median to be 50), students-wise
def f2(x):
  return abs(x-50)

def f3(x):
  return (x.max()-x.min())/100

print(df1.apply(f1))
print(df1.apply(f2, axis="columns"))
print(df1.apply(f3, axis="columns"))

series1 = pd.Series([1,2,3,4,5])
print(series1.map(np.exp))

def f4(x):
  return x+10

# print(df1.applymap(f4))
print(df1.map(f4))

          English  Hindi  Maths  Science  Social Science
Students
John           94     78     55       50              28
Aray           70     91     91       73              14
Sam            89     43     78       42              95
Jay            94     55      7       57              29
     English  Hindi  Maths  Science  Social Science
max       94     91     91       73              95
min       70     43      7       42              14
          English  Hindi  Maths  Science  Social Science
Students
John           44     28      5        0              22
Aray           20     41     41       23              36
Sam            39      7     28        8              45
Jay            44      5     43        7              21
Students
John    0.66
Aray    0.77
Sam     0.53
Jay     0.87
dtype: float64
0      2.718282
1      7.389056
2     20.085537
3     54.598150
4    148.413159
dtype: float64
          English  Hindi  Maths  Science  Social Science
Students
John          104     88     65       60              38
Aray           80    101    101       83              24
Sam            99     53     88       52             105
Jay           104     65     17       67              39

**Sorting and Ranking**

In [ ]:
# sort_index(), sort_values()
print(df1)
print(df1.sort_index())
df1.sort_values(["Science","English"],ascending=False,inplace=True)
print(df1)

# df1.rank()
# df1.rank(axis="columns")
df1.rank(method="first")

          English  Hindi  Maths  Science  Social Science
Students
Aray           70     91     91       73              14
Jay            94     55      7       57              29
John           94     78     55       50              28
Sam            89     43     78       42              95
          English  Hindi  Maths  Science  Social Science
Students
Aray           70     91     91       73              14
Jay            94     55      7       57              29
John           94     78     55       50              28
Sam            89     43     78       42              95
          English  Hindi  Maths  Science  Social Science
Students
Aray           70     91     91       73              14
Jay            94     55      7       57              29
John           94     78     55       50              28
Sam            89     43     78       42              95

          English  Hindi  Maths  Science  Social Science
Students
Aray          1.0    4.0    4.0      4.0             1.0
Jay           3.0    2.0    1.0      3.0             3.0
John          4.0    3.0    2.0      2.0             2.0
Sam           2.0    1.0    3.0      1.0             4.0

**Section A — Series and DataFrame Fundamentals**

In [ ]:
# Q1. Series Creation
# Create Series from:
# list
# numpy array
# dictionary
# scalar (with index)

import pandas as pd
import numpy as np

# series1 = pd.Series([1,2,3,4,5])
# series1.name = "Series from list"
# series1.index.name = "Index"
# print(series1)

# series2 = pd.Series(np.array([1,2,3,4,5]))
# series2.name = "Series from numpy array"
# series2.index.name = "Index"
# print(series2)

# series3 = pd.Series({"A":101,"B":102,"C":103,"D":104})
# series3.name = "Series from dictionary"
# series3.index.name = "Keys"
# print(series3)

# series4 = pd.Series([1]*10)
# print(series4)

# Q2. Attributes
# For a Series:
# values
# index
# dtype
# shape

# series1 = pd.Series(np.array([1,2,3,4,5]))
# print(series1.array)
# print(series1.values)
# print(series1.index)
# print(series1.index.values)
# print(series1.dtype)
# print(series1.shape)

# Q3. DataFrame Creation
# Create DataFrame using:
# dictionary of lists
# list of dictionaries
# numpy array
# CSV file

# df1 = pd.DataFrame({"A":[1,2,3,4,5],"B":[1,2,3,1,2],"C":[2,6,2,5,3]})
# print(df1)

# # df2 = pd.DataFrame([[1,2],[1,2]])
# list1 = [{"name":"John","marks":80},
#          {"name":"Sam","marks":70},
#          {"name":"Ray","marks":92}]

# df2 = pd.DataFrame(list1)
# print(df2)

# array1 = np.array([[1,2,3,4,5],[2,3,1,4,2],[2,1,3,2,42]])
# df3 = pd.DataFrame(array1)
# print(df3)

# csv_file_data = pd.read_csv("data.csv")
# print(type(csv_file_data))
# df4 = pd.DataFrame(csv_file_data)
# print(df4.head())
# print(type(df4),df4.index.dtype,df4.values.dtype)

# Q4. Column & Row Access
# select single column
# select multiple columns
# select rows using index
# use .loc and .iloc

# series1 = pd.Series(np.array([45,23,65,25,24]), index = list("ABCDE"))
# print(series1)

# print(series1[3])
# print(series1.loc["B"])
# print(series1.iloc[4])

# df1 = pd.DataFrame({"English":[78,56,74,38,92],"Hindi":np.random.randint(35,101,5),"Science":np.random.randint(35,101,5)}, index = "Ray Sam John Henry Mark".split())
# df1.index.name = "Students"
# df1.columns.name = "Subjects"
# print(df1,"\n")
# print(df1[np.random.choice(df1.columns)], "\n") # selects one random column from the dataframe
# print(df1[np.random.choice(df1.columns,2)], "\n") # selects two random columns from the dataframe
# print(df1[1:4], "\n")
# print(df1.loc[:,["English","Science"]],"\n")
# print(df1.loc[:,"English":"Science"],"\n")
# print(df1.iloc[2:4,-1:-3:-1], "\n")

# Q5. Index Behavior
# Create custom index
# check immutability
# rename index
# reset index

# index1 = pd.Index(list("abcde"))
# index1.name = "custom initial index"
# print(index1)
# print(type(index1))
# # index1["b"] = "c" --> gives error since index object is immutable
# index1.name = "Custom index"
# print(index1,"\n")
# print(df1)
# # df2 = df1.reset_index()
# df2 = df1.reset_index(drop=True) # drops the earlier maintained index i.e "Students" here
# print(df2)
# print(df2.index.name)

# Given two Series:
# add them
# observe NaNs
# fill missing values

# series1 = pd.Series(np.arange(5,11))
# series2 = pd.Series(np.random.randint(10,101,10))
# print(series1)
# print(series2)

# sum_series = series1 + series2
# print(sum_series)
# # print(sum_series.isna())
# # print(sum_series.isna().value_counts())

# sum_series.fillna(5, inplace=True)
# print(sum_series)

# Q7.
# Explain and demonstrate:
# 👉 Difference between .loc vs .iloc

# Q8.
# Given a DataFrame:
# extract rows where index is not continuous
# reassign index

# print(df1)
# print(df2)
# df2.index = [0,2,3,4,6]
# print(df2)
# idx_df2 = df2.index
# idx_range = pd.Index(np.arange(0,df2.index[-1]+1))
# # diff = idx_df2.difference(idx_range)
# diff = idx_range.difference(idx_df2)
# print(diff)
# diff = np.array(diff)
# diff = diff - 1
# print(diff)
# print(df2.loc[diff])
# df2.reset_index(inplace=True)
# print(df2)

**Section B — Essential Functionality**

In [ ]:
# Q9.
# reindex a Series
# introduce missing labels
# fill using forward fill (ffill)

import pandas as pd
import numpy as np

# series1 = pd.Series(np.array([5.6,4.56,8.78,9.56,10]))
# print(series1)
# series1 = series1.reindex([2,4,3,2,5])
# print(series1)

# # series1 = series1.reindex(list(series1.index).insert(2, np.nan))
# series1.iloc[2] = np.nan
# print(series1)
# series1.ffill(inplace=True)
# print(series1)

# Q10.
# Reindex DataFrame:
# reorder rows
# reorder columns
# fill missing values

# print(df1)
# # df2 = df1.reindex(columns = np.random.permutation(list(df1.columns)))
# df2 = df1.reindex(np.random.permutation(list(df1.columns)), axis=1)
# print(df2)

# # df2 = df2.reindex(index=["Sam","Henry"])
# df2 = df2.reindex(["Sam","Henry"], axis=0)
# print(df2)

# # df2 = df2.reindex(["Henry","Ray","Sam"], axis=0) #--> will give nan values for Ray now since it isn't present now in df2 but was present earlier
# # print(df2)
# df2 = df2.reindex(["Henry","Ray","Sam"], axis=0, fill_value=0)
# # df2 = df2.reindex(["Henry","Ray","Sam"], axis=0, fill_value="default")
# print(df2, df2.values.dtype)

# Q11.
# drop rows
# drop columns
# drop using index label
# drop using axis

# print(df2)
# df2.drop(columns = ["Science"], inplace=True)
# print(df2)
# print(df1)
# df3 = df1.drop(index = ["Henry"], columns = ["English"])
# print(df3)

df1 = pd.DataFrame({"English":[78,56,74,38,92],"Hindi":np.random.randint(35,101,5),"Science":np.random.randint(35,101,5)}, index = "Ray Sam John Henry Mark".split())
df1.index.name = "Students"
df1.columns.name = "Subjects"
# print(df1)
# df3 = df1.drop(index = ["Henry"], columns = ["English"])
# print(df3)
# # df3.drop(0, inplace=True) #--> gives error since 0 isn't present in index (labels)
# df3.drop(["Sam","John"], inplace=True)
# print(df3)
# df3.drop(["Hindi"], axis=1, inplace=True)
# print(df3)

# Q12.
# filter rows based on condition
# select rows where column > value
# multiple condition filtering

# condition = ((df1["English"] + df1["Hindi"] + df1["Science"])/3)>75
# print(condition)
# print(df1[condition])

# print(df1[df1["Hindi"]>90])
# print(df1[(df1["English"]+df1["Hindi"]+df1["Science"])>200])
# print(df1[(df1["English"]>80) & (df1["Hindi"]>75)])

# Q13.
# Given DataFrame:
# filter using AND/OR
# filter using .isin()
# filter using string condition

# print(df1[df1["Science"].isin(np.arange(90,101))])
# print(df1[df1.index.str.contains('R', case=False)])
# print(df1.loc[:,df1.columns.str.startswith('S')])
# print(df1[df1.index.str.endswith('ay')])

# Q14.
# Dataset: employee salary
# Tasks:
# employees earning > avg salary
# employees in specific departments
# employees with name starting with 'A'

# data = pd.read_csv("Employee_Salary_Dataset.csv")
# data = pd.read_csv("employees.csv")
# print(data.head(),"\n")

# print("mean salary:",np.mean(data["Salary"]))
# print(data[data["Salary"]>np.mean(data["Salary"])])
# print(data["Team"][data["Salary"]>np.mean(data["Salary"])])
# print(data.loc[(data["Salary"])>np.mean(data["Salary"]), "Team"])
# print(len(data["Team"][data["Salary"]>np.mean(data["Salary"])].unique()))
# print(type(pd.unique(data["Team"][data["Salary"]>np.mean(data["Salary"])])))

# dept = data["Team"].unique()
# print("departments:",dept,"\n\n")
# random_dept = np.random.choice(dept)
# print("random dept chosen:",random_dept)
# print(data[data["Team"]==random_dept])
# print(data["Team"][(data["Team"].isin(dept[1:6:2])) & (data["Team"].notna())])

# print(data[data["First Name"].str.startswith('R', na=False)])
# print(data["First Name"][data["First Name"].str.startswith('R', na=False)].unique())

# print(data[data["First Name"].str.startswith('A', na=False)])
# print(data["First Name"][data["First Name"].str.startswith('A', na=False)].unique())

# data.dropna(subset=["First Name", "Last Login Time"], inplace=True)
# print(data[data["First Name"].str.startswith('R')])
# print(data["First Name"][data["First Name"].str.startswith('R')].unique())

# Q15.
# Add two DataFrames:
# observe alignment
# handle NaN

# df3 = pd.DataFrame({"A":[1,2,3,4],"B":[2,3,5,3],"C":[5,6,7,8]}, index="first second third fourth".split())
# df4 = pd.DataFrame({"C":[2,4,5,2,5],"D":[5,2,5,2,3],"E":[5,2,5,2,4],"A":[2,5,2,5,6]},index="first second third fourth fifth".split())
# print(df3)
# print(df4)
# print((df3+df4).fillna(0))

# Q16.
# use .add() with fill_value
# perform column-wise operations
# normalize column values

# print(df3.add(df4))
# print(df3.add(df4, fill_value=0))
# print(df3.add(df4,fill_value=1))

# df3_columns = df3.columns

# df3 = (df3 - df3.min()) / (df3.max() - df3.min())
# df3.apply(lambda x : (x-x.min())/(x.max()-x.min()))
# df3["A"] = (df3["A"] - df3["A"].min()) / (df3["A"].max() - df3["A"].min())
# df3

# row_min = df3.min(axis=1)
# row_max = df3.max(axis=1)

# df3 = df3.sub(row_min, axis=0).div(row_max - row_min, axis=0)
# df3

# Q18.
# use .apply() on column
# use .map()
# use .applymap()

# df3 = df3.apply(lambda x:x/x.max())
# df3 = df3.apply(lambda x:x/x.max(), axis=1)
# print(df3)


# def f1(x):
#   return x**2

# series1 = pd.Series(np.arange(1,11,2))
# print(series1)

# series1 = series1.map(f1)
# print(series1)

# series1 = series1.apply(f1)
# print(series1)

# # series1 = series1.applymap(f1) #--> gives AttributeError since series object has no attribute applymap
# # print(series1)

# df3 = df3.applymap(f1)
# print(df3)

# df3 = df3.map(f1)
# print(df3)

# Q19.
# create custom function
# apply on rows
# transform values

# Q20.
# Create new column:
# based on multiple columns
# conditional logic

# df3["mean"] = (df3["A"] + df3["B"] + df3["C"])/3
# df3["mean"] = df3.apply(np.mean, axis=1)
# df3["mean"] = (df3.iloc[:3]).apply(np.mean, axis=0)
# df3

# df3[(df3["A"] + df3["B"] + df3["C"])>12]
# df3["High_12"] = (df3["A"] + df3["B"] + df3["C"])>12
# df3["High_12"] = ((df3["A"] + df3["B"] + df3["C"])>12).astype(int)
# df3

# Q21.
# sort by column
# sort descending
# sort multiple columns

# df3 = df3.sort_index()
# df3 = df3.sort_values(["B","C"]) #--> performs hierarchial indexing sorting first by column "B" and if identical values encountered, then sorting column "C"
# df3 = df3.sort_values("C", ascending=False)
# df3 = df3.sort_values(by=["C","B"], ascending=[True, False])

# df3["B"] = df3["B"].sort_values().values #--> though this is not recommended since it disturbs the order of rows and relationship between specific columns values according to row indices or say changes the pairs of row-wise values for columns
# df3["C"] = df3["C"].sort_values().values

# df3["B"] = df3["B"].sort_values()
# df3["C"] = df3["C"].sort_values()
# df3

# Q22.
# rank values
# dense rank vs average rank

# df3.rank()
# df3["mean"] = df3.apply(np.mean, axis=1)
# df3["average_rank"] = df3["mean"].rank()
# df3["dense rank"] = df3["mean"].rank(method="dense", ascending=False)
# print(df3)

# Q23.
# Rank students:
# within class
# overall
print(df1)
# df1["%"] = (df1["English"] + df1["Hindi"] + df1["Science"])/3
# df1["rank"] = df1["%"].rank(method="dense", ascending=False)
# df1.sort_values("rank")

# Q24.
# create duplicate index
# detect duplicates
# handle duplicates

df1_index = list(df1.index.values)
random_index = str(np.random.choice(df1_index))
# dup_index = list(df1.index.values).append(str(np.random.choice(list(df1.index.values))))
dup_index = df1_index.append(random_index)
print(dup_index)
# list(df1.index.values)
# np.random.choice(list(df1.index.values))
# str(np.random.choice(list(df1.index.values)))
# df1_index.append(str(np.random.choice(["a","b"])))
# df1_index

df1.duplicated()
df1.loc["Ray"] = [45,63,43]
df1

Subjects  English  Hindi  Science
Students
Ray            78     39       37
Sam            56     51       38
John           74     74       74
Henry          38     58       89
Mark           92     90       53
None

Subjects  English  Hindi  Science
Students
Ray            45     63       43
Sam            56     51       38
John           74     74       74
Henry          38     58       89
Mark           92     90       53

**Section C — Descriptive Statistics**

In [ ]:
# Q25.
# Compute:
# mean
# median
# std
# describe()

import pandas as pd
import numpy as np

# marks = list(np.random.randint(1,100,(3,3)))
# subjects = list("Maths Science SST".split())
# students = list("Sam Ray Hesky".split())
# dict_students = {subject:marks for subject,marks in zip(subjects,marks)}
# # print(dict_students)
# df1 = pd.DataFrame(dict_students)
# df1.index = students
# df1.index.name = "Students"
# df1.columns.name = "Subjects"
# print(df1, "\n")

# print("Overall mean marks: ",np.mean(df1))
# print("Subject wise mean marks:", df1.apply(np.mean, axis=0))
# print("Student wise mean marks:", df1.apply(np.mean, axis=1))

# print("Overall median marks:", np.median(df1))
# print("Subject wise median marks:", df1.apply(np.median, axis=0))
# print("Student wise median marks:", df1.apply(np.median, axis=1))

# print("Overall std:", np.std(df1))
# print("Subject wise std:", df1.apply(np.std, axis=0))
# print("Student wise std:", df1.apply(np.std, axis=1))

# print(type(df1.describe()))
# print(type(df1))

# Q26.
# column-wise stats
# row-wise stats
# missing values handling

# df1.iloc[1,1], df1.iloc[2,2] = [np.nan, np.nan]
# print(df1)
# print(pd.isna(df1.iat[1,1]))
# print(pd.isna(df1.iat[2,2]))
# df1.fillna(0, inplace=True)
# df1

# df1 = df1.fillna(df1.apply(np.mean, axis=0))
# df1

# Q27.
# Dataset: sales
# total revenue
# avg per category
# highest/lowest

data = pd.read_csv("sales_data.csv")
# print(data.head())
# data.describe()

# # data["Selling_Price"] = data["Unit_Price"] - data["Discount"]*data["Unit_Price"]
# data["net_sales_amount"] = data["Sales_Amount"] - data["Sales_Amount"]*data["Discount"]
# # data["profit"] = data["net_sales_amount"] - (data["Unit_Cost"]*data["Quantity_Sold"])
# data["profit"] = data["net_sales_amount"] - data["Unit_Cost"]
# # print(data.head(), "\n\n")
# print("total revenue:", np.sum(data["profit"]))

# category_df = data.loc[:,["Product_Category","profit"]]
# print(category_df)
# unique_categories = data["Product_Category"].unique()
# print(unique_categories)
# profit_dict = {}
# for category in unique_categories:
#   df = category_df.loc[category_df["Product_Category"]==category,:]
#   avg_profit_category = float(np.round(np.mean(df["profit"]),2))
#   profit_dict[category] = avg_profit_category
# print("avg profit per category:", profit_dict)
# series_category_avg_profit = pd.Series(profit_dict)
# print(series_category_avg_profit)
# print(series_category_avg_profit.rank(ascending=False).sort_values()) #--> highest value will receive rank 1

# Q28.
# compute correlation matrix
# interpret results
# detect strong relationships

is_numeric_df = data.loc[0]
is_numeric_df = is_numeric_df.to_dict()
# print(is_numeric_df)

numeric_cols = []
non_numeric_cols = []
for key,value in is_numeric_df.items():
  if type(value) in [int,float]:
    numeric_cols.append(key)
  else:
    non_numeric_cols.append(key)

# print(numeric_cols)
# print(non_numeric_cols)

data_numeric_df = data.loc[:,numeric_cols]
data_non_numeric_df = data.loc[:,non_numeric_cols]
# print(data_numeric_df.head())
print(data_non_numeric_df.head())

# data_numeric_df.corr()
# data_numeric_df.corrwith(data_numeric_df["Sales_Amount"])

# Q29.
# unique values
# value_counts
# normalize counts
# membership check

print("unique values of region:", data_non_numeric_df["Region"].unique())
print("value counts:", data_non_numeric_df["Product_Category"].value_counts())
counts_df = data_non_numeric_df["Product_Category"].value_counts()
counts_df = (counts_df - counts_df.min()) / (counts_df.max() - counts_df.min())
print(counts_df)

    Sale_Date Sales_Rep Region Product_Category Customer_Type Payment_Method  \
0  2023-02-03       Bob  North        Furniture     Returning           Cash
1  2023-04-21       Bob   West        Furniture     Returning           Cash
2  2023-09-21     David  South             Food     Returning  Bank Transfer
3  2023-08-24       Bob  South         Clothing           New    Credit Card
4  2023-03-24   Charlie   East      Electronics           New    Credit Card

  Sales_Channel Region_and_Sales_Rep
0        Online            North-Bob
1        Retail             West-Bob
2        Retail          South-David
3        Retail            South-Bob
4        Online         East-Charlie
unique values of region: ['North' 'West' 'South' 'East']
value counts: Product_Category
Clothing       268
Furniture      260
Electronics    246
Food           226
Name: count, dtype: int64
Product_Category
Clothing       1.000000
Furniture      0.809524
Electronics    0.476190
Food           0.000000
Name: count, dtype: float64