**Handling Missing Data**

In [ ]:
# missing values representation in pandas
import numpy as np
import pandas as pd

series1 = pd.Series([0.2,5.6,np.nan,4,None])
print(series1)

print(series1.isna())
print(series1.isna().sum())
print(series1.isna().value_counts())

0    0.2
1    5.6
2    NaN
3    4.0
4    NaN
dtype: float64
0    False
1    False
2     True
3    False
4     True
dtype: bool
2
False    3
True     2
Name: count, dtype: int64

Filtering missing data

In [ ]:
# we use dropna() method to filter out missing data from series or dataframe
# key parameters of dropna() method are: how (how="any", how="all") , thresh (computes minimum number of non-NA values along the indicated axis to give the filtered result) , inplace (True/False)

series1 = pd.Series([3.4,2.5,6.7,np.nan,8.6,None])
print(series1)
print(series1.isna())

print(series1[series1.notna()])
print(series1[~series1.isna()])
series1.dropna(inplace=True)
series1

0    3.4
1    2.5
2    6.7
3    NaN
4    8.6
5    NaN
dtype: float64
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
0    3.4
1    2.5
2    6.7
4    8.6
dtype: float64
0    3.4
1    2.5
2    6.7
4    8.6
dtype: float64

0    3.4
1    2.5
2    6.7
4    8.6
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.random.standard_normal((5,3)))
print(df1)

df1.iloc[2:4,:2] = np.nan
df1.iloc[1:3,2] = np.nan
df1.iloc[4,1] = np.nan
print(df1)

# filtering out missing data with just using pd.isna function and boolean indexing
print(df1[df1.iloc[:,0].notna()]) # removes rows where column 0 has null values
df1.dropna() # drops rows with any null values
df1.dropna(how="all") # drops rows with all null values
df1.dropna(thresh=2) # keeps rows (since default axis=0) with minimum 2 non-NA values
df1.dropna(thresh=3, axis=1) # keeps columns with minimum 3 non-NA values

          0         1         2
0  1.443987  1.045024  0.573378
1 -1.469269 -0.550774 -1.569309
2 -0.681484 -0.756073 -0.791779
3 -0.965641 -0.059074 -0.306446
4  0.578085 -0.054697 -1.595626
          0         1         2
0  1.443987  1.045024  0.573378
1 -1.469269 -0.550774       NaN
2       NaN       NaN       NaN
3       NaN       NaN -0.306446
4  0.578085       NaN -1.595626
          0         1         2
0  1.443987  1.045024  0.573378
1 -1.469269 -0.550774       NaN
4  0.578085       NaN -1.595626

          0         2
0  1.443987  0.573378
1 -1.469269       NaN
2       NaN       NaN
3       NaN -0.306446
4  0.578085 -1.595626

Filling in missing data

In [ ]:
# we can fill missing data using fillna() method
# key parameters of fillna() method are : value to fill missing values with (constant or dictionary for column-wise specification) , method ("ffill" or "bfill") , axis ("index" or "columns" / 0 or 1) , limit (maximum number of values to fill with during forward fill or backward fill when doing interpolation using the method argument)
print(df1)

df1.fillna(0)
replace_missing_values = {0:5.2, 1:2.4, 2:3}
df1.fillna(replace_missing_values)
df1.fillna(method="ffill")
df1.fillna(method="bfill", limit=1, axis=1)

# filling missing values column wise with their mean values
df1.fillna(df1.mean(axis=0))
# filling missing values row wise with their mean values
# df1.fillna(df1.mean(axis=1), axis=1)  # --> results in error due to non-alignment of row index values with column labels of the dataframe
# df1.T.fillna(df1.mean(axis=1), axis=0).T
df1 = df1.apply(lambda row:row.fillna(row.mean()), axis=1)
df1

          0         1         2
0  1.443987  1.045024  0.573378
1 -1.469269 -0.550774 -1.010022
2       NaN       NaN       NaN
3 -0.306446 -0.306446 -0.306446
4  0.578085 -0.508770 -1.595626

/tmp/ipykernel_1212/3115537452.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method="ffill")
/tmp/ipykernel_1212/3115537452.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method="bfill", limit=1, axis=1)

          0         1         2
0  1.443987  1.045024  0.573378
1 -1.469269 -0.550774 -1.010022
2       NaN       NaN       NaN
3 -0.306446 -0.306446 -0.306446
4  0.578085 -0.508770 -1.595626

**Data Transformation**

Removing duplicates

In [ ]:
# key methods :
# duplicated() : checks column values if any same value existed in earlier row
# drop_duplicates() : drops duplicate rows (accepts "subset" to specify which column values to refer to for removing duplicate rows)

df1 = pd.DataFrame({"k1":np.random.randint(0,6,5), "k2":np.random.randint(0,6,5), "v1":np.random.randint(0,6,5)})
print(df1)

print(df1.duplicated())
print(df1["k1"].duplicated())
# df1.drop_duplicates()
df1 = df1.drop_duplicates(subset=["k1"]) # drops rows from the dataframe corresponding to duplicate locations in k1 column
print("dropped duplicates based on k1:")
print(df1)

# print(df1.loc[:,"k1":"k2"].duplicated())
df1.drop_duplicates(subset=["k1","k2"], inplace=True) # drops rows from the dataframe where duplicate values are identified in subset formed by k1 and k2 column values
print("dropped duplicates based on [\"k1\",\"k2\"]")
print(df1)

   k1  k2  v1
0   5   5   5
1   0   5   4
2   5   5   0
3   1   0   0
4   0   1   4
0    False
1    False
2    False
3    False
4    False
dtype: bool
0    False
1    False
2     True
3    False
4     True
Name: k1, dtype: bool
dropped duplicates based on k1:
   k1  k2  v1
0   5   5   5
1   0   5   4
3   1   0   0
dropped duplicates based on ["k1","k2"]
   k1  k2  v1
0   5   5   5
1   0   5   4
3   1   0   0

Transforming data using a function or mapping

In [ ]:
# map method can be used for specifying a dictionary to map values of a column with or a function for transforming it's values
import numpy as np
import pandas as pd

df1 = pd.DataFrame({"English":np.random.randint(25,101,10), "Hindi":np.random.randint(25,101,10), "Maths":np.random.randint(25,101,10), "Social Science":np.random.randint(25,101,10)}, index=list("Rohan Akshay Sohan Shilpa Ishita Abhay Vikrant Aniket Dikshita Sandra".split()))
print("Student dataframe:")
print(df1)

# assigning a "english fluency" title to every student based on their english marks
english_marks_categories = [(df1["English"]<=30), (df1["English"]>=31) & (df1["English"]<=50), (df1["English"]>=51) & (df1["English"]<=70) , (df1["English"]>=71) & (df1["English"]<=90) , (df1["English"]>=91) & (df1["English"]<=100)]
english_titles = ["Beginner", "On way to fluency", "Fluent", "Viber", "Professional"]
english_marks_level_dict = np.select(english_marks_categories, english_titles, default="")
# print(english_marks_level_dict)
df1["english_level"] = english_marks_level_dict
# print(df1)

# assigning cities from where students belong using map function
stud_city_mapping = {key:value for key,value in zip(df1.index, np.random.choice(list("Delhi Uttar_Pradesh Bengaluru Mumbai Pune Odisha Chennai".split()), 10))}
df1["City"] = df1.index.map(stud_city_mapping)

# alternative way for passing a function to map method instead of a dictionary
def map_stud_city(stud):
  return stud_city_mapping[stud]

df1["City_from_function"] = df1.index.map(map_stud_city)
print(df1)

Student dataframe:
          English  Hindi  Maths  Social Science
Rohan          79     25     52              51
Akshay         94     81     88              60
Sohan          85     99     75              47
Shilpa         60     62     88              46
Ishita         78     81     43              84
Abhay          96     90     59              71
Vikrant        53     79     81              90
Aniket         60     75     54              78
Dikshita       95     82     96              54
Sandra         38     74     57              32
          English  Hindi  Maths  Social Science      english_level  \
Rohan          79     25     52              51              Viber
Akshay         94     81     88              60       Professional
Sohan          85     99     75              47              Viber
Shilpa         60     62     88              46             Fluent
Ishita         78     81     43              84              Viber
Abhay          96     90     59              71       Professional
Vikrant        53     79     81              90             Fluent
Aniket         60     75     54              78             Fluent
Dikshita       95     82     96              54       Professional
Sandra         38     74     57              32  On way to fluency

                   City City_from_function
Rohan     Uttar_Pradesh      Uttar_Pradesh
Akshay            Delhi              Delhi
Sohan            Odisha             Odisha
Shilpa             Pune               Pune
Ishita          Chennai            Chennai
Abhay           Chennai            Chennai
Vikrant          Odisha             Odisha
Aniket           Odisha             Odisha
Dikshita          Delhi              Delhi
Sandra           Odisha             Odisha

Discretization and Binning

In [ ]:
# convert continuous data into bins or intervals
import numpy as np
import pandas as pd
numbers_list = np.random.randint(1,12,10) # creates a list of 5 random numbers from range 1 to 12
print(numbers_list)

# converting numbers list into bins
categories = [0,1,5,6,8,10,11]
numbers_categories = pd.cut(numbers_list, categories)
print(numbers_categories)
print(numbers_categories.codes)  # prints interval codes
print(numbers_categories.categories)  # prints categories/intervals
print(numbers_categories.categories[4])  # prints 5th category/interval of the interval index object

[ 6  7  3  1  8  8  8  9  5 11]
[(5, 6], (6, 8], (1, 5], (0, 1], (6, 8], (6, 8], (6, 8], (8, 10], (1, 5], (10, 11]]
Categories (6, interval[int64, right]): [(0, 1] < (1, 5] < (5, 6] < (6, 8] < (8, 10] < (10, 11]]
[2 3 1 0 3 3 3 4 1 5]
IntervalIndex([(0, 1], (1, 5], (5, 6], (6, 8], (8, 10], (10, 11]], dtype='interval[int64, right]')
(8, 10]

In [ ]:
# adding maths level column into student dataframe by dividing maths numbers data (maths column values) into specific bins
maths_bins = [0,40,60,80,100]
maths_levels = ["School_level","College_level","Statistics_level","Data_science_level"]
df1["maths_level"] = pd.cut(df1["Maths"], maths_bins, labels=maths_levels)
print(df1.loc[:,["Maths","maths_level"]])

          Maths         maths_level
Rohan        52       College_level
Akshay       88  Data_science_level
Sohan        75    Statistics_level
Shilpa       88  Data_science_level
Ishita       43       College_level
Abhay        59       College_level
Vikrant      81  Data_science_level
Aniket       54       College_level
Dikshita     96  Data_science_level
Sandra       57       College_level

In [ ]:
print(pd.cut(df1["Maths"], 5, precision=2))  # cuts maths column values data into 5 categories

Rohan       (42.95, 53.6]
Akshay       (85.4, 96.0]
Sohan        (74.8, 85.4]
Shilpa       (85.4, 96.0]
Ishita      (42.95, 53.6]
Abhay        (53.6, 64.2]
Vikrant      (74.8, 85.4]
Aniket       (53.6, 64.2]
Dikshita     (85.4, 96.0]
Sandra       (53.6, 64.2]
Name: Maths, dtype: category
Categories (5, interval[float64, right]): [(42.95, 53.6] < (53.6, 64.2] < (64.2, 74.8] <
                                           (74.8, 85.4] < (85.4, 96.0]]

In [ ]:
# difference between pd.cut and pd.qcut
data = np.random.standard_normal(1000)
data = data.round(2)
print(pd.cut(data,5).categories)  # divides data values into equal-width intervals
print(pd.cut(data,5).value_counts())
print(pd.qcut(data,5).categories)  # divides data values into equal-size (frequency) intervals
print(pd.qcut(data,5).value_counts())

IntervalIndex([(-3.567, -2.206], (-2.206, -0.852],  (-0.852, 0.502],
                 (0.502, 1.856],    (1.856, 3.21]],
              dtype='interval[float64, right]')
(-3.567, -2.206]     16
(-2.206, -0.852]    181
(-0.852, 0.502]     484
(0.502, 1.856]      289
(1.856, 3.21]        30
Name: count, dtype: int64
IntervalIndex([(-3.561, -0.84], (-0.84, -0.23], (-0.23, 0.27], (0.27, 0.87],
               (0.87, 3.21]],
              dtype='interval[float64, right]')
(-3.561, -0.84]    202
(-0.84, -0.23]     202
(-0.23, 0.27]      197
(0.27, 0.87]       200
(0.87, 3.21]       199
Name: count, dtype: int64

In [ ]:
series = pd.Series([1,2,None], dtype=pd.Int64Dtype())
print(series.isna())
print(series[2])
print(series[2] is pd.NA)

0    False
1    False
2     True
dtype: bool
<NA>
True

Computing Indicator/Dummy Variables

In [ ]:
# map method can be used for specifying a dictionary to map values of a column with or a function for transforming it's values
import numpy as np
import pandas as pd

df1 = pd.DataFrame({"English":np.random.randint(25,101,10), "Hindi":np.random.randint(25,101,10), "Maths":np.random.randint(25,101,10), "Social Science":np.random.randint(25,101,10)}, index=list("Rohan Akshay Sohan Shilpa Ishita Abhay Vikrant Aniket Dikshita Sandra".split()))
print("Student dataframe:")
# print(df1)

# assigning a "english fluency" title to every student based on their english marks
english_marks_categories = [(df1["English"]<=30), (df1["English"]>=31) & (df1["English"]<=50), (df1["English"]>=51) & (df1["English"]<=70) , (df1["English"]>=71) & (df1["English"]<=90) , (df1["English"]>=91) & (df1["English"]<=100)]
english_titles = ["Beginner", "On way to fluency", "Fluent", "Viber", "Professional"]
english_marks_level_dict = np.select(english_marks_categories, english_titles, default="")
# print(english_marks_level_dict)
df1["english_level"] = english_marks_level_dict
# print(df1)

# assigning cities from where students belong using map function
stud_city_mapping = {key:value for key,value in zip(df1.index, np.random.choice(list("Delhi Uttar_Pradesh Bengaluru Mumbai Pune Odisha Chennai".split()), 10))}
df1["City"] = df1.index.map(stud_city_mapping)
print(df1)

Student dataframe:
          English  Hindi  Maths  Social Science      english_level  \
Rohan          26     53     77              64           Beginner
Akshay         53     37     47              65             Fluent
Sohan          30     55     80              34           Beginner
Shilpa         49     32     61              58  On way to fluency
Ishita         64     64     29              60             Fluent
Abhay          73     82     91              63              Viber
Vikrant        26     56     60              51           Beginner
Aniket         66     28     53              42             Fluent
Dikshita       48     69     59              83  On way to fluency
Sandra         97     77     96              37       Professional

                   City
Rohan           Chennai
Akshay    Uttar_Pradesh
Sohan     Uttar_Pradesh
Shilpa           Odisha
Ishita            Delhi
Abhay             Delhi
Vikrant       Bengaluru
Aniket            Delhi
Dikshita         Mumbai
Sandra    Uttar_Pradesh

In [ ]:
# print(pd.get_dummies(df1["City"], dtype=int))
stud_df_with_dummies = df1.join(pd.get_dummies(df1["City"], prefix="City_", dtype=int))
print(stud_df_with_dummies)

          English  Hindi  Maths  Social Science      english_level  \
Rohan          26     53     77              64           Beginner
Akshay         53     37     47              65             Fluent
Sohan          30     55     80              34           Beginner
Shilpa         49     32     61              58  On way to fluency
Ishita         64     64     29              60             Fluent
Abhay          73     82     91              63              Viber
Vikrant        26     56     60              51           Beginner
Aniket         66     28     53              42             Fluent
Dikshita       48     69     59              83  On way to fluency
Sandra         97     77     96              37       Professional

                   City  City__Bengaluru  City__Chennai  City__Delhi  \
Rohan           Chennai                0              1            0
Akshay    Uttar_Pradesh                0              0            0
Sohan     Uttar_Pradesh                0              0            0
Shilpa           Odisha                0              0            0
Ishita            Delhi                0              0            1
Abhay             Delhi                0              0            1
Vikrant       Bengaluru                1              0            0
Aniket            Delhi                0              0            1
Dikshita         Mumbai                0              0            0
Sandra    Uttar_Pradesh                0              0            0

          City__Mumbai  City__Odisha  City__Uttar_Pradesh
Rohan                0             0                    0
Akshay               0             0                    1
Sohan                0             0                    1
Shilpa               0             1                    0
Ishita               0             0                    0
Abhay                0             0                    0
Vikrant              0             0                    0
Aniket               0             0                    0
Dikshita             1             0                    0
Sandra               0             0                    1

**String Manipulation**

Python's built-in string methods

In [ ]:
# key python's built-in string methods are:
# - split()
# - strip() , rstrip(), lstrip()
# - ljust(), rjust()
# - count()
# - replace()
# - join()
# - index()
# - find()

str1 = "hi! my name is ABC"
str1_words = str1.split()
# print(str1, ":", str1_words)

str2 = "  hello, what's  ,going ,on    "
str2_words = [word.strip() for word in str2.split(",")]
# print(str2, str2_words, sep=":")

str3 = "     hi hi how are you man man man??      "
# print(str3.ljust(len(str3.strip())))
# print(str3.strip().ljust(60, "-"))
# print(str3.strip().rjust(60, "-"))

str3 = str3.strip()
print(str3)
print(str3.count("hi"))
print(str3.count(" "))
print(str3.index("?"))
# print(str3.index("A"))  --> returns error since "A" isn't present in string
print(str3.find("man"))
print(str3.find("1"))  # --> returns -1 if element not present
str3 = str3.replace("man","-")
print(str3)
".".join("hi how are you?")
"manA".upper()
"AAMAAASi n A".lower().replace(" ","")

hi hi how are you man man man??
2
7
29
18
-1
hi hi how are you - - -??

'aamaaasina'

**Questions (Data Loading)**

In [ ]:
# 💡 Q1 — CSV Mastery

# Load a CSV and:

# read only specific columns
# handle missing values (na_values)
# set index column
# skip rows

import pandas as pd
csv_file = pd.read_csv("employees.csv")
# print(csv_file.head())
# print(csv_file.iloc[:,[2,4]])
csv_cols = pd.read_csv("employees.csv", usecols=[0,1,2])  # --> usecols argument for reading specific columns
# print(csv_cols.head())
csv_cols_s = pd.read_csv("employees.csv", usecols= lambda x: x[0] in ['s','S'])  # only reads columns with names starting with letter s
# print(csv_cols_s.head())

# csv_file.iloc[:3,-1].isna()
csv_na = pd.read_csv("employees.csv", keep_default_na=False, na_values={"Team":"Marketing"})
# print(csv_na.head())
# print(csv_na.iloc[:3,-1].isna())

csv_index = pd.read_csv("employees.csv", index_col = "First Name")
# print(csv_index.head())

print(csv_file.head(5))
csv_skiprows = pd.read_csv("employees.csv", skiprows = [1,3])  # --> removes the first and third rows of original data since row 0 is the header row with column names
print(csv_skiprows.head(5))

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services
  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
1      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
2      Larry    Male  1/24/1998         4:47 PM  101004    1.389
3     Dennis    Male  4/18/1987         1:35 AM  115163   10.125
4       Ruby  Female  8/17/1987         4:20 PM   65476   10.012

  Senior Management             Team
0              True              NaN
1              True          Finance
2              True  Client Services
3             False            Legal
4              True          Product

In [ ]:
# 💡 Q2 — Large File Handling
# Simulate:
# read large dataset in chunks
# compute mean of a column

# 👉 Use:
# pd.read_csv(..., chunksize=...)

import pandas as pd
import numpy as np

# loading a 500 MB dataset in chunks to ensure memory support (dataset contains around 10,48,576 rows)
file_reader = pd.read_csv("bq-20260318-110718_analytics_deliveries_report_flodata.csv", chunksize=100000)  # reads file in chunks of 1,00,000 rows each

sum_col = 0
rows_chunk = 0

for chunk in file_reader:
  print(chunk.head(3).iloc[:,-2:])
  print(chunk["delivery_days"].dtype)
  print("rows in chunk:",len(chunk))
  rows_chunk += len(chunk)
  sum_col += np.sum(chunk["delivery_days"])

print("total sum of delivery days:", sum_col)
print("total rows in the dataset:", rows_chunk)
print("mean delivery days:", sum_col/rows_chunk)

  delivered_date  delivery_days
0     2026-02-21       1.856968
1     2026-02-02       3.981076
2     2026-02-13       1.869387
float64
rows in chunk: 100000
       delivered_date  delivery_days
100000     2026-03-14       0.747824
100001     2025-10-11       1.074086
100002     2025-11-29       0.924838
float64
rows in chunk: 100000
       delivered_date  delivery_days
200000     2026-01-06       0.631944
200001     2026-01-08       0.681319
200002     2026-03-17       0.896192
float64
rows in chunk: 100000
       delivered_date  delivery_days
300000     2025-12-17       0.729468
300001     2025-11-06       0.610069
300002     2026-03-11       0.798947
float64
rows in chunk: 100000
       delivered_date  delivery_days
400000     2025-10-02       0.637188
400001     2025-11-01       0.739340
400002     2025-11-13       0.615000
float64
rows in chunk: 100000
       delivered_date  delivery_days
500000     2025-10-07       0.702894
500001     2026-02-27       0.695104
500002     2026-01-03       0.738241
float64
rows in chunk: 100000
       delivered_date  delivery_days
600000     2025-11-29       0.474792
600001     2026-03-10       0.998808
600002     2026-02-26       0.902222
float64
rows in chunk: 100000
       delivered_date  delivery_days
700000     2026-01-15       1.729850
700001     2025-10-07       4.876424
700002     2025-10-03       1.808692
float64
rows in chunk: 100000
       delivered_date  delivery_days
800000     2025-12-04       2.757616
800001     2025-12-09       4.073345
800002     2026-01-06       2.727419
float64
rows in chunk: 100000
       delivered_date  delivery_days
900000     2025-11-12       1.716678
900001     2025-11-13       2.972558
900002     2025-11-13       1.963264
float64
rows in chunk: 100000
        delivered_date  delivery_days
1000000     2026-03-02       0.844190
1000001     2026-01-29       0.695671
1000002     2025-11-06       0.672593
float64
rows in chunk: 100000
        delivered_date  delivery_days
1100000     2025-10-06       2.676528
1100001     2025-12-06       3.036655
1100002     2025-10-08       0.656308
float64
rows in chunk: 100000
        delivered_date  delivery_days
1200000     2026-02-10       0.393588
1200001     2026-01-15       0.690949
1200002     2025-11-20       0.239387
float64
rows in chunk: 100000
        delivered_date  delivery_days
1300000     2026-03-10       1.978646
1300001     2025-11-18       0.796516
1300002     2025-11-08       0.696343
float64
rows in chunk: 100000
        delivered_date  delivery_days
1400000     2025-12-09       0.610498
1400001     2025-11-12       0.871296
1400002     2025-11-08       0.660799
float64
rows in chunk: 100000
        delivered_date  delivery_days
1500000     2025-11-03       2.466250
1500001     2025-10-30       1.607396
1500002     2026-02-26       0.732731
float64
rows in chunk: 100000
        delivered_date  delivery_days
1600000     2025-12-23       0.788738
1600001     2025-11-01       0.562118
1600002     2025-12-01       1.758727
float64
rows in chunk: 100000
        delivered_date  delivery_days
1700000     2025-11-25       0.942604
1700001     2025-09-25       0.810093
1700002     2025-10-18       0.653646
float64
rows in chunk: 100000
        delivered_date  delivery_days
1800000     2025-12-06       0.842164
1800001     2025-11-17       0.692500
1800002     2025-11-03       0.878322
float64
rows in chunk: 100000
        delivered_date  delivery_days
1900000     2026-03-07       0.626192
1900001     2026-02-13       0.830208
1900002     2025-11-29       0.662280
float64
rows in chunk: 100000
        delivered_date  delivery_days
2000000     2026-02-18       0.734618
2000001     2026-02-27       0.937130
2000002     2026-02-14       0.883287
float64
rows in chunk: 100000
        delivered_date  delivery_days
2100000     2026-02-24       3.614734
2100001     2025-12-08       4.447234
2100002     2025-12-02       6.647569
float64
rows in chunk: 100000
        delivered_date  delivery_days
2200000     2025-12-17       1.884468
2200001     2026-01-15       4.706817
2200002     2025-09-24       1.520035
float64
rows in chunk: 100000
        delivered_date  delivery_days
2300000     2025-10-18       1.790451
2300001     2025-12-30       3.756863
2300002     2026-03-04       2.717431
float64
rows in chunk: 100000
        delivered_date  delivery_days
2400000     2025-09-18       3.559433
2400001     2025-10-14       1.788692
2400002     2025-09-25       2.591852
float64
rows in chunk: 100000
        delivered_date  delivery_days
2500000     2025-11-29       0.962801
2500001     2025-10-06       1.971424
2500002     2026-01-27       0.855046
float64
rows in chunk: 100000
        delivered_date  delivery_days
2600000     2026-01-09       0.778762
2600001     2025-09-30       0.700336
2600002     2025-11-12       0.731308
float64
rows in chunk: 100000
        delivered_date  delivery_days
2700000     2026-01-08       0.753854
2700001     2025-12-09       0.801759
2700002     2025-10-11       0.683032
float64
rows in chunk: 100000
        delivered_date  delivery_days
2800000     2025-11-07       0.727187
2800001     2025-12-12       3.470243
2800002     2025-12-19       7.869271
float64
rows in chunk: 100000
        delivered_date  delivery_days
2900000     2025-12-02       0.571539
2900001     2025-12-23       0.701076
2900002     2025-11-17       0.844514
float64
rows in chunk: 100000
        delivered_date  delivery_days
3000000     2025-09-20       0.774537
3000001     2026-01-23       0.697882
3000002     2025-11-17       2.682164
float64
rows in chunk: 100000
        delivered_date  delivery_days
3100000     2025-11-13       0.261435
3100001     2026-02-23       0.276632
3100002     2025-12-17       0.583750
float64
rows in chunk: 100000
        delivered_date  delivery_days
3200000     2026-02-03       0.908206
3200001     2026-03-17       0.969560
3200002     2025-12-16       1.156910
float64
rows in chunk: 100000
        delivered_date  delivery_days
3300000     2026-03-11       1.528507
3300001     2025-12-07       1.801725
3300002     2026-01-30       0.531053
float64
rows in chunk: 100000
        delivered_date  delivery_days
3400000     2026-01-05       5.927674
3400001     2026-01-28       4.654769
3400002     2026-01-29       1.810764
float64
rows in chunk: 100000
        delivered_date  delivery_days
3500000     2025-11-07       0.731447
3500001     2026-01-15       0.713634
3500002     2025-11-03       1.725208
float64
rows in chunk: 100000
        delivered_date  delivery_days
3600000     2025-10-16       0.767199
3600001     2025-10-09       0.861146
3600002     2026-02-24       1.705961
float64
rows in chunk: 100000
        delivered_date  delivery_days
3700000     2025-10-16       0.603819
3700001     2025-11-03       0.637083
3700002     2025-12-09       4.995023
float64
rows in chunk: 100000
        delivered_date  delivery_days
3800000     2026-02-13       0.639641
3800001     2025-12-01       1.863576
3800002     2026-01-08       0.632917
float64
rows in chunk: 100000
        delivered_date  delivery_days
3900000     2026-01-14       0.697106
3900001     2025-12-14       2.813264
3900002     2025-12-29       2.187743
float64
rows in chunk: 100000
        delivered_date  delivery_days
4000000     2026-03-07       2.767708
4000001     2026-03-07       2.666574
4000002     2026-02-06       4.677755
float64
rows in chunk: 100000
        delivered_date  delivery_days
4100000     2025-10-01       1.792558
4100001     2026-02-26       1.617072
4100002     2025-12-05       1.035208
float64
rows in chunk: 100000
        delivered_date  delivery_days
4200000     2026-02-20       0.727025
4200001     2026-03-11       0.698495
4200002     2025-12-20       0.454641
float64
rows in chunk: 100000
        delivered_date  delivery_days
4300000     2026-03-04       0.436852
4300001     2025-11-19       0.612535
4300002     2025-12-30       0.864074
float64
rows in chunk: 100000
        delivered_date  delivery_days
4400000     2026-01-03       0.402257
4400001     2026-02-25       0.217998
4400002     2025-12-12       0.736296
float64
rows in chunk: 100000
        delivered_date  delivery_days
4500000     2026-01-12       0.439549
4500001     2025-10-14       0.241852
4500002     2025-12-05       0.598252
float64
rows in chunk: 100000
        delivered_date  delivery_days
4600000     2026-02-20       1.947905
4600001     2025-11-11       3.740451
4600002     2026-01-31       1.821470
float64
rows in chunk: 100000
        delivered_date  delivery_days
4700000     2026-02-05       1.759734
4700001     2026-02-05       2.207419
4700002     2025-12-02       4.055706
float64
rows in chunk: 100000
        delivered_date  delivery_days
4800000     2025-10-29       0.717789
4800001     2025-09-23       3.076331
4800002     2026-02-26       0.685544
float64
rows in chunk: 100000
        delivered_date  delivery_days
4900000     2026-02-17       0.592419
4900001     2025-12-21       1.663218
4900002     2025-12-21       0.813102
float64
rows in chunk: 100000
        delivered_date  delivery_days
5000000     2025-12-12       9.629653
5000001     2025-12-19       0.621215
5000002     2025-10-17       1.089907
float64
rows in chunk: 100000
        delivered_date  delivery_days
5100000     2026-03-02       0.570729
5100001     2025-11-28       1.689919
5100002     2026-02-06       1.003530
float64
rows in chunk: 100000
        delivered_date  delivery_days
5200000     2025-10-01       1.639479
5200001     2025-11-17       3.022060
5200002     2026-02-02       5.601817
float64
rows in chunk: 100000
        delivered_date  delivery_days
5300000     2025-11-20       0.842465
5300001     2025-10-03       1.562292
5300002     2025-10-10       1.826088
float64
rows in chunk: 100000
        delivered_date  delivery_days
5400000     2025-11-14       1.014213
5400001     2025-11-04       1.667072
5400002     2025-10-10       0.566227
float64
rows in chunk: 54070
total sum of delivery days: 9124516.484675927
total rows in the dataset: 5454070
mean delivery days: 1.6729738497444893

In [ ]:
# 💡 Q3 — JSON Handling

# Given JSON:

# load into DataFrame
# normalize nested JSON

# 👉 Use:

# pd.read_json()
# pd.json_normalize()

json_file = pd.read_json("airports.json")
print(json_file.head())
print(json_file.shape, type(json_file), "\n")

# json_file_normalized = pd.json_normalize("airports.json") #--> returns error since json_normalize accepts list or dictionary but here we passed a string, it cannot read a file on it's own
json_file_normalized = pd.json_normalize(json_file["airports"])
print(json_file_normalized.head())

                                            airports
0  {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1  {'code': 'PEK', 'name': 'Beijing Capital Inter...
2  {'code': 'DXB', 'name': 'Dubai International',...
3  {'code': 'LAX', 'name': 'Los Angeles Internati...
4  {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...
(30, 1) <class 'pandas.core.frame.DataFrame'>

  code                                      name         city country  \
0  ATL  Hartsfield-Jackson Atlanta International      Atlanta      US
1  PEK             Beijing Capital International      Beijing      CN
2  DXB                       Dubai International        Dubai      AE
3  LAX                 Los Angeles International  Los Angeles      US
4  HND                              Tokyo Haneda        Tokyo      JP

       lat       lon
0  33.6407  -84.4277
1  40.0801  116.5846
2  25.2528   55.3644
3  33.9425 -118.4081
4  35.5494  139.7798

In [ ]:
# 💡 Q4 — Excel + Multi-sheet
# read specific sheet
# read multiple sheets
# combine into one DataFrame

excel_file = pd.read_excel("sheetX.xlsx")
# print(excel_file.head())
# print(excel_file.shape, type(excel_file))

excel_file_sheet = pd.read_excel("sheetX.xlsx", sheet_name = 1) # reads second sheet of the excel file
# print(excel_file_sheet.head())

excel_file_sheets = pd.read_excel("sheetX.xlsx", sheet_name = [0,1]) # creates a dictionary of dataframes (of both sheets) with key 0 having the first sheet dataframe as value and index 1 having the second sheet dataframe as value
# print(excel_file_sheets)
# print(type(excel_file_sheets)) # returns dict as the type since it is a dictionary of the dataframes
# print(type(excel_file_sheets[0])) # returns dataframe since it is the first sheet's dataframe

excel_file_combined_df = pd.merge(excel_file_sheets[0], excel_file_sheets[1], on="Date")
print(excel_file_combined_df.head())

        Date Metro_x  Lower Bound(Yhat lower)_x  Upper Bound(Yhat upper)_x  \
0 2025-03-26     ARI                          0                         18
1 2025-03-26     ARI                          0                         18
2 2025-03-26     ARI                          0                         18
3 2025-03-26     ARI                          0                         18
4 2025-03-26     ARI                          0                         18

   Capped Upper Bound_x  Forecast(Yhat)_x  yhat_lower(mt)  yhat_upper(mt)  \
0                     6                 5               0              18
1                     6                 5               0              18
2                     6                 5               0              18
3                     6                 5               0              18
4                     6                 5               0              18

   Capped Upper Bound(mt)  yhat(mt)  ...  Metro_y Lower Bound(Yhat lower)_y  \
0                       6         5  ...      COL                       144
1                       6         5  ...      MAD                        62
2                       6         5  ...      GRA                       134
3                       6         5  ...      CHI                       471
4                       6         5  ...      NYC                      1644

  Upper Bound(Yhat upper)_y Capped Upper Bound_y  Forecast(Yhat)_y  actual_y  \
0                       692                  500               385     465.0
1                       585                  393               302     323.0
2                       328                  299               230     225.0
3                      2945                 1970              1515    1490.0
4                      3629                 3409              2622    2868.0

   Delta  Unnamed: 8  Unnamed: 9  Unnamed: 10
0   80.0         NaN         NaN          NaN
1   21.0         NaN         NaN          NaN
2   -5.0         NaN         NaN          NaN
3  -25.0         NaN         NaN          NaN
4  246.0         NaN         NaN          NaN

[5 rows x 23 columns]

In [ ]:
# 💡 Q5 — API Data (IMPORTANT)

# Use any API (even dummy):

# fetch JSON
# convert to DataFrame
# basic cleaning

# 👉 Use:

# import requests

import requests
# url = "https://www.simpliance.in/India/LEI/holiday_list/delhi/2026"
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
# print(resp)

api_data = resp.json()
# print(type(api_data))

# print(api_data) # contains a list of dictionaries
# print(api_data[0]) # returns the dictionary present at the first index of the list
# print(api_data[0]["title"])

api_data_df = pd.DataFrame(api_data, columns = ["number", "title", "labels", "state"])
print(api_data_df.head())

# api_data_normalize = pd.json_normalize(api_data[0])
# print(api_data_normalize.head())

   number                                              title  \
0   65048  CLN: remove unnecessary usage of option_contex...
1   65047  ENH/BUG: Utilize `_values_for_json` in `Series...
2   65046             PERF: add no_nans fast path in nancorr
3   65045  DOC: clarify Series alignment in DataFrame.assign
4   65044  DEPR: deprecate lsuffix/rsuffix in DataFrame.j...

                                              labels state
0  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open
1  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open
2  [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open
3                                                 []  open
4  [{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4...  open

**Questions (Data Cleaning)**

In [ ]:
# Q1.

# detect missing values
# count missing values (column + row)

data = pd.read_csv("employees.csv")
# print(data.head())
print(data.isna().sum())  # prints total number of nan values per column
print(data.isna().sum(axis=1))  # prints total number of nan values per row
print(data[data.isna().sum(axis=1)>=3])  # prints rows with 3 or more than 3 nan values

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64
0      0
1      1
2      0
3      0
4      0
      ..
995    1
996    0
997    0
998    0
999    0
Length: 1000, dtype: int64
    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
23         NaN    Male   6/14/2012         4:19 PM  125792    5.042
32         NaN    Male   8/21/1998         2:27 PM  122340    6.417
51         NaN     NaN  12/17/2011         8:29 AM   41126   14.009
139        NaN  Female   10/3/1990         1:08 AM  132373   10.527
174        NaN     NaN   9/18/2007         6:59 PM   40297    6.185
253        NaN     NaN   4/28/2003         3:01 AM  113732   10.391
382        NaN  Female   4/18/1996         3:57 PM  107024   12.182
521        NaN     NaN   9/25/1981         9:59 AM   83895   17.971
567        NaN  Female    4/1/1980         8:04 PM   48141   12.605
626        NaN  Female   4/13/1997         8:03 AM  131755    2.930
628        NaN     NaN    9/2/1988        12:49 PM  147309    1.702
774        NaN  Female   6/18/2000         7:36 AM  106428   10.867
783        NaN     NaN   4/15/1991         3:39 AM  132505   13.592
826        NaN     NaN    8/1/1988         1:35 AM   87103    5.665
951        NaN  Female   9/14/2010         5:19 AM  143638    9.662

    Senior Management             Team
23                NaN              NaN
32                NaN              NaN
51                NaN            Sales
139               NaN              NaN
174               NaN  Client Services
253               NaN            Sales
382               NaN              NaN
521               NaN      Engineering
567               NaN              NaN
626               NaN              NaN
628               NaN     Distribution
774               NaN              NaN
783               NaN          Product
826               NaN              NaN
951               NaN              NaN

In [ ]:
# Q2.

# drop rows with missing values
# drop columns with missing values
# conditional dropping

# data_copy = data.copy()
# print(data_copy.head())
# print(data_copy.shape)
# data_copy.dropna(inplace=True)
# print(data_copy.shape)

# data_copy = data.copy()
# nan_cols_series = data_copy.isna().sum()>=1
# nan_cols = list(nan_cols_series[nan_cols_series==True].index)
# print("columns with nan values:",nan_cols)
# print(data_copy.shape)
# data_copy.dropna(axis=1, inplace=True)
# print(data_copy.shape)

# data_copy = data.copy()
# print(data_copy.shape)
# # data_copy.dropna(subset=["First Name"], inplace=True)  # drops rows where "First Name" column has null values
# data_copy.dropna(subset=["First Name","Team"], inplace=True)  # drops rows where "First Name" or "Team" column has null values
# print(data_copy.shape)

# data_copy = data.copy()
# # drop columns with more than 3 nan values
# nan_cols_series = data_copy.isna().sum()>=3
# nan_cols = list(nan_cols_series[nan_cols_series==True].index)
# print(nan_cols)
# print(data_copy.shape)
# data_copy.dropna(subset=nan_cols, inplace=True)
# print(data_copy.shape)

data_copy = data.copy()
print("teams:", data_copy["Team"].unique())
team = np.random.choice(data_copy["Team"].unique())
print("random team chosen to remove:", team)
data_copy = data_copy[data_copy["Team"]!=team]
print("teams after conditional dropping:", data_copy["Team"].unique())

teams: ['Marketing' nan 'Finance' 'Client Services' 'Legal' 'Product'
 'Engineering' 'Business Development' 'Human Resources' 'Sales'
 'Distribution']
random team chosen to remove: Sales
teams after conditional dropping: ['Marketing' nan 'Finance' 'Client Services' 'Legal' 'Product'
 'Engineering' 'Business Development' 'Human Resources' 'Distribution']

In [ ]:
# Q3.
# Fill missing values using:
# mean
# median
# forward fill
# backward fill
# group-wise fill
# Example:
# df.groupby("Dept")["Salary"].transform(lambda x: x.fillna(x.mean()))

sales_data = pd.read_csv("sales_data.csv")
# print(sales_data.head())
# print(sales_data.shape)
# print(sales_data.isna().sum())

sales_data.iloc[40:65, 4:7] = np.nan
print(sales_data.isna().sum())

# sales_data_idx = list(sales_data[sales_data["Sales_Amount"].isna()].index)
# print(sales_data_idx)
sales_data.fillna({"Sales_Amount":np.mean(sales_data["Sales_Amount"])}, inplace=True)  # np.mean automatically skips rows with nan values
# print(sales_data.isna().sum())
# print(sales_data.iloc[sales_data_idx, 4])

sales_data.fillna({"Quantity_Sold":np.nanmedian(sales_data["Quantity_Sold"])}, inplace=True)  # np.median doesn't skips rows with nan values automatically, whereas np.nanmedian does
# print(sales_data.isna().sum())

sales_data["Product_Category"].fillna(method="ffill", limit=2, inplace=True)
print(sales_data.isna().sum())
sales_data["Product_Category"].fillna(method="bfill", limit=3, inplace=True)
print(sales_data.isna().sum())

Product_ID               0
Sale_Date                0
Sales_Rep                0
Region                   0
Sales_Amount            25
Quantity_Sold           25
Product_Category        25
Unit_Cost                0
Unit_Price               0
Customer_Type            0
Discount                 0
Payment_Method           0
Sales_Channel            0
Region_and_Sales_Rep     0
dtype: int64
Product_ID               0
Sale_Date                0
Sales_Rep                0
Region                   0
Sales_Amount             0
Quantity_Sold            0
Product_Category        23
Unit_Cost                0
Unit_Price               0
Customer_Type            0
Discount                 0
Payment_Method           0
Sales_Channel            0
Region_and_Sales_Rep     0
dtype: int64
Product_ID               0
Sale_Date                0
Sales_Rep                0
Region                   0
Sales_Amount             0
Quantity_Sold            0
Product_Category        20
Unit_Cost                0
Unit_Price               0
Customer_Type            0
Discount                 0
Payment_Method           0
Sales_Channel            0
Region_and_Sales_Rep     0
dtype: int64

/tmp/ipykernel_7395/2766138975.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales_data["Product_Category"].fillna(method="ffill", limit=2, inplace=True)
/tmp/ipykernel_7395/2766138975.py:28: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sales_data["Product_Category"].fillna(method="ffill", limit=2, inplace=True)
/tmp/ipykernel_7395/2766138975.py:30: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  sales_data["Product_Category"].fillna(method="bfill", limit=3, inplace=True)

In [ ]:
# Q4.

# remove duplicates
# detect duplicates

print(sales_data.isna().sum())
sales_data.dropna(inplace=True)
print(sales_data.isna().sum())

print(sales_data.duplicated())
print("number of duplicate rows:", sales_data.duplicated().sum())
print("shape:", sales_data.shape)
sales_data.drop_duplicates(inplace=True)
print("number of duplicate rows:", sales_data.duplicated().sum())
print("shape:", sales_data.shape)

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64
Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64
0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 980, dtype: bool
number of duplicate rows: 0
shape: (980, 14)
number of duplicate rows: 0
shape: (980, 14)

In [ ]:
# Q5.

# map values
# replace values
# rename columns

sales_data = pd.read_csv("sales_data.csv")
# print(sales_data.head())
region_prime_mapping = {"North":"Premium", "South":"Medium", "East":"Low", "West":"High"}
sales_data["Region_Premium_Category"] = sales_data["Region"].map(region_prime_mapping)
# print(sales_data.head())

# sales_data["Region_Premium_Category"].replace("High", "High_Premium", inplace=True)
sales_data["Region_Premium_Category"].replace(["High","Low"], ["High_Premium","Low_Premium"], inplace=True)
# print(sales_data.head())

sales_data.rename(columns={"Region_Premium_Category":"Region_Premiumness"}, inplace=True)
print(sales_data.head())

   Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18
1        1093  2023-04-21       Bob   West       4384.02             17
2        1015  2023-09-21     David  South       4631.23             30
3        1072  2023-08-24       Bob  South       2167.94             39
4        1061  2023-03-24   Charlie   East       3750.20             13

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09
1        Furniture    3816.39     4209.44     Returning      0.11
2             Food     261.56      371.40     Returning      0.20
3         Clothing    4330.03     4467.75           New      0.02
4      Electronics     637.37      692.71           New      0.08

  Payment_Method Sales_Channel Region_and_Sales_Rep Region_Premiumness
0           Cash        Online            North-Bob            Premium
1           Cash        Retail             West-Bob       High_Premium
2  Bank Transfer        Retail          South-David             Medium
3    Credit Card        Retail            South-Bob             Medium
4    Credit Card        Online         East-Charlie        Low_Premium

/tmp/ipykernel_7395/3134706653.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales_data["Region_Premium_Category"].replace(["High","Low"], ["High_Premium","Low_Premium"], inplace=True)

In [ ]:
# Q6.
# Dataset: messy salary dataset
# convert strings → numbers
# fix inconsistent categories
# standardize formats

emp_data = pd.read_csv("employees.csv")
print(emp_data.head())
# print(emp_data.dtype)  # --> gives error since dataframe doesn't have any datatype
print(emp_data["Bonus %"].dtype)
emp_data["Bonus %"] = emp_data["Bonus %"].astype(str)
print(emp_data["Bonus %"].dtype)
# emp_data["Bonus %"] = emp_data["Bonus %"].astype(int)
# emp_data["Bonus %"] = emp_data["Bonus %"].astype('Int64')
emp_data["Bonus %"] = emp_data["Bonus %"].astype(float)
print(emp_data["Bonus %"].dtype)

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services
float64
object
float64

In [ ]:
# Q7.
# bin data using pd.cut()
# create age groups

import numpy as np
import pandas as pd

# data = np.random.randint(0,101,10)
# print(data)

# bins = [0,20,35,50,70,100]

# data_bins = pd.cut(data, bins)
# print(data_bins)
# print(data_bins.tolist())  # gives only the interval values

ages = np.random.randint(20,51,20)
print("ages:", ages)

bins_ages = [20,30,40,50]

ages_bins = pd.cut(ages, bins_ages, labels = ["young", "middle-aged", "senior"])
print(ages_bins)
print(ages_bins.value_counts())

ages: [38 28 47 27 30 32 23 22 46 27 34 46 49 38 49 48 50 50 30 35]
['middle-aged', 'young', 'senior', 'young', 'young', ..., 'senior', 'senior', 'senior', 'young', 'middle-aged']
Length: 20
Categories (3, object): ['young' < 'middle-aged' < 'senior']
young          7
middle-aged    5
senior         8
Name: count, dtype: int64

In [ ]:
# Q8.

# use pd.qcut()
# create quantile bins

data = np.random.randint(0,1001,100)
print(data[:5])
print("min value in data:", np.min(data))
print("max value in data:", np.max(data))

# bins = [0,100,300,450,680,720,900,1000]  --> no need of bins here since pd.qcut divides data into quantiles with equal frequency of items in each quantile

data_bins = pd.qcut(data, 4)
print(data_bins)
print(data_bins.value_counts())

[768 685 808 918 847]
min value in data: 4
max value in data: 998
[(760.5, 998.0], (503.5, 760.5], (760.5, 998.0], (760.5, 998.0], (760.5, 998.0], ..., (3.999, 207.75], (503.5, 760.5], (3.999, 207.75], (503.5, 760.5], (3.999, 207.75]]
Length: 100
Categories (4, interval[float64, right]): [(3.999, 207.75] < (207.75, 503.5] < (503.5, 760.5] <
                                           (760.5, 998.0]]
(3.999, 207.75]    25
(207.75, 503.5]    25
(503.5, 760.5]     25
(760.5, 998.0]     25
Name: count, dtype: int64

In [ ]:
# Q10.
# detect outliers using IQR

data = np.random.randint(0,101,10)
data[5:10:2] = [312,-5,500]
print(data)

# IQR method for outlier detection
# Outliers are data values that fall below the value of Q1-1.5*IQR or fall above the value of Q3+1.5*IQR
# IQR = Q3-Q1

q3 = np.quantile(data,0.75)
q1 = np.quantile(data,0.25)
# iqr = np.quantile(data,0.75) - np.quantile(data,0.25)
iqr = q3 - q1
# print("outlier values present in data:", data[(data<(-1.5*iqr)) | (data>1.5*iqr)])
print("outlier values present in data:", data[(data<(q1-(1.5*iqr))) | (data>(q3+(1.5*iqr)))])

[ 61  71  75  40  93 312  44  -5   2 500]
outlier values present in data: [312 500]

In [ ]:
# Q11.

# remove outliers
# cap outliers

data_outliers = np.array(data[(data<(q1-(1.5*iqr))) | (data>(q3+(1.5*iqr)))])
data = np.array(data)
print("outliers in data:", data_outliers)

data_copy = data.copy()

print("data with outliers:", data)
data = data[~np.isin(data,data_outliers)]
print("data without outliers:", data)

print("original data copy:", data_copy)
data_copy = np.where(np.isin(data_copy, data_outliers), 1000, data_copy)
print("data copy after capping outlier values:", data_copy)

outliers in data: [312 500]
data with outliers: [ 61  71  75  40  93 312  44  -5   2 500]
data without outliers: [61 71 75 40 93 44 -5  2]
original data copy: [ 61  71  75  40  93 312  44  -5   2 500]
data copy after capping outlier values: [  61   71   75   40   93 1000   44   -5    2 1000]

In [ ]:
# Q12.
# detect outliers per group

emp_data = pd.read_csv("employees.csv")
print(emp_data.head())

emp_data.loc[50:61:2, "Salary"] = 10000000
emp_data.loc[100:116:3, "Bonus %"] = 1000
# detecting outliers in salary values and bonus % separately using IQR method
q3_salary = np.quantile(emp_data["Salary"], 0.75)
q1_salary = np.quantile(emp_data["Salary"], 0.25)

q3_bonus = np.quantile(emp_data["Bonus %"], 0.75)
q1_bonus = np.quantile(emp_data["Bonus %"], 0.25)
# iqr_salary = np.quantile(emp_data["Salary"], 0.75) - np.quantile(emp_data["Salary"], 0.25)
# iqr_bonus = np.quantile(emp_data["Bonus %"], 0.75) - np.quantile(emp_data["Bonus %"], 0.25)

iqr_salary = q3_salary - q1_salary
iqr_bonus = q3_bonus - q1_bonus

salary_outliers = emp_data["Salary"][((emp_data["Salary"])<(q1_salary-(1.5*iqr_salary))) |((emp_data["Salary"])>(q3_salary+(1.5*iqr_salary)))]
bonus_outliers = emp_data["Bonus %"][((emp_data["Bonus %"])<(q1_bonus-(1.5*iqr_bonus))) | ((emp_data["Bonus %"])>(q3_bonus+(1.5*iqr_bonus)))]

print("outliers in salary:", len(salary_outliers))
print(salary_outliers)
print("outliers in bonus:", len(bonus_outliers))
print(bonus_outliers)

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services
outliers in salary: 6
50    10000000
52    10000000
54    10000000
56    10000000
58    10000000
60    10000000
Name: Salary, dtype: int64
outliers in bonus: 6
100    1000.0
103    1000.0
106    1000.0
109    1000.0
112    1000.0
115    1000.0
Name: Bonus %, dtype: float64

In [ ]:
# Q13.
# random sampling
# stratified sampling

# print(emp_data.head())
sample_10 = emp_data.sample(n=10)  # random sample of 10 exact rows of the dataframe
sample_20_pct = emp_data.sample(frac=0.2)  # random sample of 20% of data
print(sample_10)
print(sample_10.shape)
print(sample_20_pct)
print(sample_20_pct.shape)

    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
333    Shirley  Female    6/8/1986         2:25 AM  110061    7.494
708      Steve    Male   1/11/2002         9:17 PM   51821    1.197
354  Elizabeth  Female  11/10/2005         4:56 AM  106406    1.782
974      Harry    Male   8/30/2011         6:31 PM   67656   16.455
83       Shawn    Male   9/23/2005         2:55 AM  148115    6.539
644  Katherine  Female   8/13/1996        12:21 AM  149908   18.912
938       Mark     NaN    9/9/2006        12:27 PM   44836    2.657
169   Michelle  Female   11/4/1996         9:34 PM   53754    5.455
86       Annie     NaN   9/29/2007        12:11 AM  103495   17.290
281     Arthur    Male    1/1/2014         7:46 PM  134610    6.147

    Senior Management                  Team
333             False       Client Services
708              True                 Legal
354              True                 Legal
974              True       Client Services
83               True               Finance
644             False               Finance
938             False       Client Services
169              True               Product
86               True  Business Development
281              True       Human Resources
(10, 8)
    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
80      Gerald     NaN   3/17/1995        12:50 AM  137126   15.602
770  Katherine  Female   9/22/2006         8:08 PM   72002   13.178
284     Brenda  Female   10/6/2005         9:33 PM  141521    4.337
736       Judy  Female    4/5/2011         1:44 AM   48668   11.716
252      Ralph    Male  11/11/2004         1:35 AM   71896    4.232
..         ...     ...         ...             ...     ...      ...
229     Jeremy    Male    6/8/2000        12:15 AM   49542    1.679
661      Craig    Male   8/21/1995         2:38 AM  123876    4.225
646  Elizabeth  Female   2/21/2010         7:02 AM   79145   19.780
694    Barbara  Female  11/12/2011        12:35 AM   85718   13.326
344      Scott    Male   5/12/2009         4:36 AM   58248    3.914

    Senior Management                  Team
80               True                 Sales
770              True               Product
284             False       Client Services
736              True               Product
252              True             Marketing
..                ...                   ...
229              True          Distribution
661             False           Engineering
646             False               Finance
694             False       Client Services
344             False  Business Development

[200 rows x 8 columns]
(200, 8)

In [ ]:
# Q14.

# one-hot encoding
# pd.get_dummies()

# print(emp_data.head())
team_dummies = pd.get_dummies(emp_data["Team"], prefix="Team_", dtype=int)
# print(team_dummies)
emp_data_copy = emp_data.copy()
emp_data_copy = emp_data_copy.join(team_dummies)
print(emp_data_copy.head(3))
print(team_dummies.sum())

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858

  Senior Management       Team  Team__Business Development  \
0              True  Marketing                           0
1              True        NaN                           0
2             False    Finance                           0

   Team__Client Services  Team__Distribution  Team__Engineering  \
0                      0                   0                  0
1                      0                   0                  0
2                      0                   0                  0

   Team__Finance  Team__Human Resources  Team__Legal  Team__Marketing  \
0              0                      0            0                1
1              0                      0            0                0
2              1                      0            0                0

   Team__Product  Team__Sales
0              0            0
1              0            0
2              0            0
Team__Business Development    101
Team__Client Services         106
Team__Distribution             90
Team__Engineering              92
Team__Finance                 102
Team__Human Resources          91
Team__Legal                    88
Team__Marketing                98
Team__Product                  95
Team__Sales                    94
dtype: int64

In [ ]:
# Q15.

# drop first column
# avoid dummy trap

print(emp_data_copy.head())
emp_data_copy.drop(emp_data_copy.iloc[:,0].name, axis=1, inplace=True)
print(emp_data_copy.head())

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team  Team__Business Development  \
0              True        Marketing                           0
1              True              NaN                           0
2             False          Finance                           0
3              True          Finance                           0
4              True  Client Services                           0

   Team__Client Services  Team__Distribution  Team__Engineering  \
0                      0                   0                  0
1                      0                   0                  0
2                      0                   0                  0
3                      0                   0                  0
4                      1                   0                  0

   Team__Finance  Team__Human Resources  Team__Legal  Team__Marketing  \
0              0                      0            0                1
1              0                      0            0                0
2              1                      0            0                0
3              1                      0            0                0
4              0                      0            0                0

   Team__Product  Team__Sales
0              0            0
1              0            0
2              0            0
3              0            0
4              0            0
   Gender Start Date Last Login Time  Salary  Bonus % Senior Management  \
0    Male   8/6/1993        12:42 PM   97308    6.945              True
1    Male  3/31/1996         6:53 AM   61933    4.170              True
2  Female  4/23/1993        11:17 AM  130590   11.858             False
3    Male   3/4/2005         1:00 PM  138705    9.340              True
4    Male  1/24/1998         4:47 PM  101004    1.389              True

              Team  Team__Business Development  Team__Client Services  \
0        Marketing                           0                      0
1              NaN                           0                      0
2          Finance                           0                      0
3          Finance                           0                      0
4  Client Services                           0                      1

   Team__Distribution  Team__Engineering  Team__Finance  \
0                   0                  0              0
1                   0                  0              0
2                   0                  0              1
3                   0                  0              1
4                   0                  0              0

   Team__Human Resources  Team__Legal  Team__Marketing  Team__Product  \
0                      0            0                1              0
1                      0            0                0              0
2                      0            0                0              0
3                      0            0                0              0
4                      0            0                0              0

   Team__Sales
0            0
1            0
2            0
3            0
4            0

In [ ]:
# avoiding dummy trap
print(emp_data.head())

emp_data_copy = emp_data.join(pd.get_dummies(emp_data["Gender"], prefix="Gender_", dtype=int, drop_first=True))  # drops the first column so that statistical and predictive models understand the data efficiently, reduces multicollinearity since all the other column values can easily be calculated based on the first column values
print(emp_data_copy.head())

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services
  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team  Gender__Male
0              True        Marketing             1
1              True              NaN             1
2             False          Finance             0
3              True          Finance             1
4              True  Client Services             1

In [ ]:
# Q16.
# lower/upper
# strip
# replace

str1 = "Hello! How are you doing??"
print(str1.upper())
print(str1.lower())

str2 = "    Hey, what are you doing    "
print(str2.strip())
str2 = str2.replace("g","-")
print(str2)

HELLO! HOW ARE YOU DOING??
hello! how are you doing??
Hey, what are you doing
    Hey, what are you doin-

In [ ]:
# Q17.
# extract using regex
# split columns

import re

text ='''ABC abcd@email.com
EFG efgh@google.com
rag ragi@outlook.com
def def@YAHOO.com
'''
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"
regex = re.compile(pattern, flags=re.IGNORECASE)
print(regex.findall(text))

data = pd.Series({"ABC":"abcd@email.com", "EFG":"efgh@google.com", "rag":"ragi@outlook.com", "def":"def@YAHOO.com"})

pattern_extract = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex_extract = re.compile(pattern, flags=re.IGNORECASE)
print(data.str.findall(pattern_extract, flags=re.IGNORECASE))
matches = data.str.findall(pattern_extract, flags=re.IGNORECASE).str[0]
print(matches)

['abcd@email.com', 'efgh@google.com', 'ragi@outlook.com', 'def@YAHOO.com']
ABC      [(abcd, email, com)]
EFG     [(efgh, google, com)]
rag    [(ragi, outlook, com)]
def       [(def, YAHOO, com)]
dtype: object
ABC    abcd
EFG    efgh
rag    ragi
def     def
dtype: object

In [ ]:
# Q19.

# convert to category
# check memory usage

import pandas as pd
import numpy as np
import sys

emp_data = pd.read_csv("employees.csv")
print(emp_data.head())
print(emp_data["Team"].dtype, sys.getsizeof(emp_data["Team"]), emp_data["Team"].memory_usage(deep=True))

emp_data["Team"] = emp_data["Team"].astype(pd.CategoricalDtype())
print(emp_data["Team"].dtype, sys.getsizeof(emp_data["Team"]), emp_data["Team"].memory_usage(deep=True))

  First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0    Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1     Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2      Maria  Female  4/23/1993        11:17 AM  130590   11.858
3      Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4      Larry    Male  1/24/1998         4:47 PM  101004    1.389

  Senior Management             Team
0              True        Marketing
1              True              NaN
2             False          Finance
3              True          Finance
4              True  Client Services
object 58671 58639
category 2060 2028

In [ ]:
# Q20.

# reorder categories
# filter categorical data

# print(emp_data["Team"].cat.categories)
print(emp_data["Team"].isna().sum())
emp_data.dropna(subset=["Team"], inplace=True)
print(emp_data["Team"].isna().sum())
# print(emp_data["Team"][:5])
print("initial order of categories:", emp_data["Team"].cat.categories)
emp_categories = list(emp_data["Team"].cat.categories)
# shuffled_categories = np.random.shuffle(emp_categories)  #--> shuffles the list in place, assigns none to the object
shuffled_categories = np.random.permutation(emp_categories)
print("shuffled order of categories:", shuffled_categories)
emp_data["Team"] = emp_data["Team"].cat.set_categories(shuffled_categories)
print(emp_data["Team"][:5])

print(emp_data[emp_data["Team"].isin(["Business Development","Marketing"])])

0
0
initial order of categories: Index(['Human Resources', 'Legal', 'Sales', 'Business Development', 'Product',
       'Finance', 'Distribution', 'Engineering', 'Client Services',
       'Marketing'],
      dtype='object')
shuffled order of categories: ['Finance' 'Business Development' 'Product' 'Legal' 'Client Services'
 'Distribution' 'Sales' 'Human Resources' 'Marketing' 'Engineering']
0          Marketing
2            Finance
3            Finance
4    Client Services
5              Legal
Name: Team, dtype: category
Categories (10, object): ['Finance', 'Business Development', 'Product', 'Legal', ..., 'Sales',
                          'Human Resources', 'Marketing', 'Engineering']
    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
9      Frances  Female    8/8/2002         6:51 AM  139852    7.524
21     Matthew    Male    9/5/1995         2:12 AM  100612   13.645
26       Craig    Male   2/27/2000         7:45 AM   37598    7.757
33        Jean  Female  12/18/1993         9:07 AM  119082   16.180
..         ...     ...         ...             ...     ...      ...
973    Russell    Male   5/10/2013        11:08 PM  137359   11.105
986      Donna  Female  11/26/1982         7:04 AM   82871   17.999
991       Rose  Female   8/25/2002         5:12 AM  134505   11.051
994     George    Male   6/21/2013         5:47 PM   98874    4.479
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985

    Senior Management                  Team
0                True             Marketing
9                True  Business Development
21              False             Marketing
26               True             Marketing
33              False  Business Development
..                ...                   ...
973             False  Business Development
986             False             Marketing
991              True             Marketing
994              True             Marketing
998             False  Business Development

[199 rows x 8 columns]